### ISSUE TITLE
Modelling TODO

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#16]
Weapons:
* [X] USP (pistol)
* [X] SMG II (submachine gun)
* [X] TRJ (revolver)
* [X] block manipulator (custom physgun)
* [X] AX50 (sniper)
* [X] RPG (rocket launcher)
* [x] UTS15 (shotgun)
* [x] KSR1 (assault rifle)

Blocks:
* [X] Wood
* [X] Metal
* [ ] #39
* [ ] #38

Props:
* [X] Store touchscreen
* [X] Bogroll (With viewmodel)
* [X] Repair tool
* [x] Medkit
* [x] Deployable ammo

**Comment by ShadowBrian** [comment]
This needs another look over in terms of weapons we actually want, how many of each class of weapon (fire rate and all that) rather than directly ripping the list from a shooty game, so I can find interesting weapons within each class instead of just making it unoriginal.

**Comment by xezno** [comment]
I'll have a look at the different weapons we'll need in a bit
