### ISSUE TITLE
Audio TODO

### ISSUE THREAD

**Issue by ShadowBrian** [apetavern/sbox-fortwars#17]
- [x] SMGII - Shooting, reloading
- [ ] #41
- [x] USP - Shooting, reloading
- [x] TRJ - Shooting, reloading
- [x] AIAX50 - Shooting, reloading
- [x] KSR1 - Shooting, reloading
- [ ] #42
- [ ] #43
- [ ] Shop - general UI interaction sounds
- [x] CTF sounds, flag grab, capture, drop, return
- [ ] #40
