### ISSUE TITLE
Particles TODO

### ISSUE THREAD

**Issue by ShadowBrian** [apetavern/sbox-fortwars#18]
- [x] RPG Rocket trail
- [x] RPG Rocket explosion
- [ ] #44
- [x] Muzzle flash (possibly use the Grubs one)
- [ ] #45
